public class Calculadora {
    public static decimal soma(decimal num1, decimal num2){
        Decimal result = num1 + num2;
        return result;
    }
    public static decimal subtracao(decimal num1, decimal num2){
        Decimal result = num1 - num2;
        return result;
    }
    public static decimal divisao(decimal num1, decimal num2){
        Decimal result = num1 / num2;
        return result;
    }
    public static decimal multiplicacao(decimal num1, decimal num2){
        Decimal result = num1 * num2;
        return result;
    }
}